@url=localhost:3000
@id=briv

###
POST http://{{url}}/characters/{{id}}/damage HTTP/1.1
content-type: application/json

{
    "damageParts": [
        {
            "type": "slashing",
            "amount": 5
        }
    ]
}

###
POST http://{{url}}/characters/{{id}}/heal HTTP/1.1
content-type: application/json

{
    "amount": 3
}

###
POST http://{{url}}/characters/{{id}}/temporary-hit-points HTTP/1.1
content-type: application/json

{
    "amount": 5
}