name: Build & Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install packages
        run: pnpm install

      - name: Run eslint tests
        run: pnpm run lint

      - name: Build apps
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test
