name: Build & Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install packages
        run: npm install

      - name: Run eslint tests
        run: npm run lint

      - name: Build apps
        run: npm run build

      - name: Run unit tests
        run: npm run test